image:
  name: ghcr.io/quantified-uncertainty/metaforecast
  tag: ''

# Secret; you should create this in your k8s cluster.
envSecret: metaforecast-env

jobs:
  scheduler:
    command: ['ts-node', '-T', 'src/backend/flow/doEverythingForScheduler.ts']
    schedule: '0 3 * * *' # every day at 3am
  frontpage:
    command: ['ts-node', '-T', 'src/backend/index.ts', 'frontpage']
    schedule: '0 6 * * *' # every day at 6am
